version: 2.1

orbs: 
  kubernetes: circleci/kubernetes@1.3.0
  aws-cli: circleci/aws-cli@2.1.0

#Define runner executor once for use throughout the pipeline
executors:
  k8s-runner:
    machine: true
    resource_class: jtreutel/runner-test-k8s-2022

#Define list of microservices and the k8s objects that need to be deployed for each
matrix-params: &matrix-params
  parameters:
    microservice: [frontend, redis-master, redis-replica]
    object: [deployment, service]


jobs:
  checkout-code:
    # This job does not need to be run on-prem
    docker:
      - image: cimg/base:2022.03
    # We are caching data generated in a cloud container and passing it to our on-prem CircleCI Runner
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
          - .
  deploy-apps-to-cluster:
    parameters:
      # Name of microservice and object that will be deployed
      microservice: 
        type: string
      object:
        type: string
    executor: k8s-runner
    steps:
      - attach_workspace:
          at: .
      # Install utilities if necessary
      - aws-cli/setup:
          profile-name: default
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig
      # Deploy k8s object
      - kubernetes/create-or-update-resource:
          get-rollout-status: false #doesn't work with services
          resource-file-path: manifests/<< parameters.microservice >>-<< parameters.object >>.yml
          resource-name: << parameters.object >>/<< parameters.microservice >>
          show-kubectl-command: true
      - run: 
          name: Get port and IP of service and store in BASH_ENV for use in next steps
          command: echo "export SVC_PORT_AND_IP=\"$(kubectl get svc << parameters.microservice >> -o=jsonpath='{.spec.clusterIP}'):$(kubectl get svc << parameters.microservice >> -o=jsonpath='{.spec.ports[0].port}')\"" >> $BASH_ENV
      # Wait for service to become available (only run this on jobs that deploy a service)
      # Get port and IP of service and store in BASH_ENV for use in next steps
      - run:
          name: Get port and IP of service and store in BASH_ENV for use in next steps
          command: |
            if [ "<< parameters.object >>" == "service" ]; then \
              echo "export SVC_PORT_AND_IP=\"$(kubectl get svc << parameters.microservice >> -o=jsonpath='{.spec.clusterIP}'):$(kubectl get svc << parameters.microservice >> -o=jsonpath='{.spec.ports[0].port}')\"" >> $BASH_ENV;
            fi
      - run: |
          if [ "<< parameters.object >>" == "service" ]; then \
            if [ ! -f "/usr/local/bin/dockerize" ]; then \
              wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz && \
              sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz && rm dockerize-linux-amd64-v0.6.1.tar.gz; \
            fi
            dockerize -wait "tcp://$SVC_PORT_AND_IP" -timeout 1m;
            mkdir -p svc_ips && echo $SVC_PORT_AND_IP > svc_ips/svc-<< parameters.microservice >>.txt
          fi
      - persist_to_workspace:
          root: .
          paths:
          - svc_ips/*

  execute-tests:
    executor: k8s-runner
    steps:
      - attach_workspace:
          at: .
      - run: mkdir test_results
      # Run a "test" that gets contents of Angular app running on recently deployed pod
      - run: curl "$(cat svc_ips/svc-frontend.txt)" | tee test_results/angular.txt
      # Upload test result to CircleCI UI
      - store_artifacts:
          path: test_results/angular.txt
          destination: curl-angular-results.txt

  delete-apps-from-cluster:
    parameters:
      # Name of microservice and object that will be deployed
      microservice: 
        type: string
      object:
        type: string
    executor: k8s-runner
    steps:
      # Install utilities if necessaryzs
      - aws-cli/setup:
          profile-name: default
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig
      # Clean up deployed resources
      - kubernetes/delete-resource:
          now: true
          resource-names: << parameters.microservice >>
          resource-types: << parameters.object >>
          wait: true

workflows:
  testing:
    jobs:
      - checkout-code
      - deploy-apps-to-cluster:
          matrix:
            <<: *matrix-params
          requires:
            - checkout-code
          context: kubeconfig       
      - execute-tests:
          requires:
            - deploy-apps-to-cluster
      - manual-approval:
          type: approval
          requires:
            - execute-tests
      - delete-apps-from-cluster:
          matrix:
            <<: *matrix-params
          requires:
            - manual-approval
            #- execute-tests
          context: kubeconfig       
