apiVersion: v1
kind: Service
metadata:
  name: angular-app
  labels:
    run: angular-app
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      targetPort: 80
      port: 80
    - name: https
      protocol: TCP
      targetPort: 443
      port: 443
  selector:
    run: angular-app