apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  labels:
    run: nginx-app
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      targetPort: 8080
      port: 80
  selector:
    run: nginx-app